#%RAML 1.0
---

title: laprassl
baseUri: ${baseUri}/${version}
version: v1
mediaType: application/json

/profile
  displayName: Profile
  post:
    description: create a profile
    body:
      application/json:
        type: |
          {
            "name": {
              "type": "string",
              "required": true
            },
            "expiry": {
              "type": "number",
              "required": true
            },
            "subject": {
              "C": {
                "type": "string",
                "required": false
              },
              "ST": {
                "type": "string",
                "required": false
              },
              "L": {
                "type": "string",
                "required": false
              },
              "O": {
                "type": "string",
                "required": false
              },
              "OU": {
                "type": "string",
                "required": false
              }
            },
            "basicConstraints": {
              "cA": {
                "type": "boolean",
                "required": false
              },
              "pathLenConstraints": {
                "type": "number",
                "required": false
              }
            },
            "keyUsage": {
              "digitalSignature": {
                "type": "boolean",
                "required": false
              },
              "nonRepudiation": {
                "type": "boolean",
                "required": false
              },
              "keyEncipherment": {
                "type": "boolean",
                "required": false
              },
              "dataEncipherment": {
                "type": "boolean",
                "required": false
              },
              "keyAgreement": {
                "type": "boolean",
                "required": false
              },
              "keyCertSign": {
                "type": "boolean",
                "required": false
              },
              "cRLSign": {
                "type": "boolean",
                "required": false
              },
              "encipherOnly": {
                "type": "boolean",
                "required": false
              },
              "decipherOnly": {
                "type": "boolean",
                "required": false
              }
            }
          }

        example: |
          {
            "name": "rootcas"
            "expiry": 365
          }
      responses:
        201:
          body:
            application/json:
              type: |
                {
                  "status": {
                    "type": "number",
                    "required": true
                  },
                  "reason": {
                    "type": "string",
                    "required": true
                  }
                }
              example: |
                {
                  "status": "201",
                  "reason": "Created"
                }

        401:
          body:
            application/json:
              example:
                 {
                  "status": "401",
                  "reason": "missing or wrong api key"
                }               

        500:
          body:
            application/json:
              example: |
                {
                  "status": "500",
                  "reason": "database issue"
                }
