#%RAML 1.0
---

title: laprassl
baseUri: ${baseUri}/${version}
version: v1
mediaType: application/json

/profile:
  displayName: Profile
  post:
    description: create a profile
    body:
      application/json:
        type: |
          {
            "name": {
              "type": "string",
              "required": true
            },
            "expiry": {
              "type": "number",
              "required": true
            },
            "subject": {
              "C": {
                "type": "string",
                "required": false
              },
              "ST": {
                "type": "string",
                "required": false
              },
              "L": {
                "type": "string",
                "required": false
              },
              "O": {
                "type": "string",
                "required": false
              },
              "OU": {
                "type": "string",
                "required": false
              }
            },
            "basicConstraints": {
              "cA": {
                "type": "boolean",
                "required": false
              },
              "pathLenConstraints": {
                "type": "number",
                "required": false
              }
            },
            "keyUsage": {
              "digitalSignature": {
                "type": "boolean",
                "required": false
              },
              "nonRepudiation": {
                "type": "boolean",
                "required": false
              },
              "keyEncipherment": {
                "type": "boolean",
                "required": false
              },
              "dataEncipherment": {
                "type": "boolean",
                "required": false
              },
              "keyAgreement": {
                "type": "boolean",
                "required": false
              },
              "keyCertSign": {
                "type": "boolean",
                "required": false
              },
              "cRLSign": {
                "type": "boolean",
                "required": false
              },
              "encipherOnly": {
                "type": "boolean",
                "required": false
              },
              "decipherOnly": {
                "type": "boolean",
                "required": false
              }
            }
          }

        example: |
          {
            "name": "rootcas"
            "expiry": 365
          }
      responses:
        201:
          body:
            application/json:
              type: |
                {
                  "status": {
                    "type": "number",
                    "required": true
                  },
                  "reason": {
                    "type": "string",
                    "required": true
                  }
                }

              example: |
                {
                  "status": "201",
                  "reason": "Created"
                }

        401:
          body:
            application/json:
              example:
                 {
                  "status": "401",
                  "reason": "missing or wrong api key"
                }               

        500:
          body:
            application/json:
              example: |
                {
                  "status": "500",
                  "reason": "database issue"
                }

/x509:
  displayName: x509

  /key:
    displayName: Key
    post:
      description: create a new rsa or ec key
      body:
        application/json:
          type: |
            {
              "keytype": {
                "type": "string",
                "description": "must be 'rsa' or 'ec'",
                "required": true,
              },
              "keysize": {
                "type": "number",
                "description": "must be set if 'keytype' is of value 'rsa'",
                "required", false
              }
            }

          example: |
            {
              "keytype": "rsa",
              "keysize": 4096
            }

      responses:
        201:
          body:
            application/json:
              type: |
                {
                  "status": {
                    "type": "number",
                    "required": true
                  },
                  "reason": {
                    "type": "string",
                    "required": true
                  },
                  "key": {
                    "type": "string",
                    "required": true
                  }
                }

              example: |
                {
                  "status": "201",
                  "reason": "Created",
                  "key": "<PEM_STRING>"
                }

  /crt:
    displayName: CRT
    description: create a new x509 self-issued certificate
    /{signer}:
      displayName: CRT
      post:
        description: create a new x509 certificate issued by signer
        body:
          application/json:
            type: |
              {
                "profile": {
                  "type": "string",
                  "required": true
                },
                "key": {
                  "type": "string",
                  "description": "PEM encoded string of the private key",
                  "required": true
                },
                "x509": {
                  "cn": {
                    "type": "string",
                    "required": true
                  }
                },
                "token": {
                  "type": "string",
                  "description": "a random key for signing certificates with this key",
                  "required", false
                }
              }

          example: |
            {
              "profile": "root-ca",
              "key": "<PEM_STRING>",
              "x509": {
                "cn": "my awesome ca"
              },
              "token": "my-secret-token"
            }

        responses:
          201:
            body:
              application/json:
                type: |
                  {
                    "status": {
                      "type": "number",
                      "required": true
                    },
                    "reason": {
                      "type": "string",
                      "required": true
                    },
                    "crt": {
                      "type": "string",
                      "required": true
                    }
                  }

          403:
            body:
              application/json:
                type: |
                  {
                    "status": {
                      "type": "number",
                      "required": true
                    },
                    "reason": {
                      "type": "string",
                      "required": true
                    }
                  }

          404:
            body:
              application/json:
                type: |
                  {
                    "status": {
                      "type": "number",
                      "required": true
                    },
                    "reason": {
                      "type": "string",
                      "required": true
                    }
                  }
